### ISSUE TITLE
所有二级页面都打不开

### ISSUE THREAD

**Issue by lolimay** [openkraken/gallery#16]
```
E/flutter (24045): #1      AssetsBundle.resolve (package:kraken/src/launcher/bundle.dart:190:22)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #2      KrakenBundle.getBundle (package:kraken/src/launcher/bundle.dart:69:5)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #3      KrakenController.loadBundle (package:kraken/src/launcher/controller.dart:707:17)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #4      _KrakenRenderObjectElement.mount (package:kraken/widget.dart:907:5)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045):
I/flutter (24045): Kraken getting bundle for contextId: 1, path: demos/todomvc/build/kraken/index.js
E/flutter (24045): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Unable to load asset: demos/gallery/build/kraken/demos/todomvc/build/kraken/index.js
E/flutter (24045): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:224:7)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #1      AssetsBundle.resolve (package:kraken/src/launcher/bundle.dart:190:22)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #2      KrakenBundle.getBundle (package:kraken/src/launcher/bundle.dart:69:5)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #3      KrakenController.loadBundle (package:kraken/src/launcher/controller.dart:707:17)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #4      _KrakenRenderObjectElement.mount (package:kraken/widget.dart:907:5)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045):
I/flutter (24045): Kraken getting bundle for contextId: 1, path: demos/order/build/kraken/index.js
E/flutter (24045): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Unable to load asset: demos/gallery/build/kraken/demos/order/build/kraken/index.js
E/flutter (24045): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:224:7)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #1      AssetsBundle.resolve (package:kraken/src/launcher/bundle.dart:190:22)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #2      KrakenBundle.getBundle (package:kraken/src/launcher/bundle.dart:69:5)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #3      KrakenController.loadBundle (package:kraken/src/launcher/controller.dart:707:17)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #4      _KrakenRenderObjectElement.mount (package:kraken/widget.dart:907:5)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045):
I/flutter (24045): Kraken getting bundle for contextId: 1, path: demos/anime/build/kraken/index.js
E/flutter (24045): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Unable to load asset: demos/gallery/build/kraken/demos/anime/build/kraken/index.js
E/flutter (24045): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:224:7)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #1      AssetsBundle.resolve (package:kraken/src/launcher/bundle.dart:190:22)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #2      KrakenBundle.getBundle (package:kraken/src/launcher/bundle.dart:69:5)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #3      KrakenController.loadBundle (package:kraken/src/launcher/controller.dart:707:17)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #4      _KrakenRenderObjectElement.mount (package:kraken/widget.dart:907:5)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045):
I/flutter (24045): Kraken getting bundle for contextId: 1, path: demos/anime/build/kraken/index.js
E/flutter (24045): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Unable to load asset: demos/gallery/build/kraken/demos/anime/build/kraken/index.js
E/flutter (24045): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:224:7)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #1      AssetsBundle.resolve (package:kraken/src/launcher/bundle.dart:190:22)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #2      KrakenBundle.getBundle (package:kraken/src/launcher/bundle.dart:69:5)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #3      KrakenController.loadBundle (package:kraken/src/launcher/controller.dart:707:17)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045): #4      _KrakenRenderObjectElement.mount (package:kraken/widget.dart:907:5)
E/flutter (24045): <asynchronous suspension>
E/flutter (24045):
```

**Comment by wssgcg1213** [comment]
需要先构建 js bundle, 先执行  `node scripts/build_demos.js`
